### ISSUE TITLE
UTF-8 Problems

### ISSUE THREAD

**Issue by xatapult** [xproc/xproc.org#10]
There seem to be UTF-8 encoding problems building the pages... 

For instance. Somwehere I have the text: _the word “pipeline” very literal_

It shows as: 

![image](https://user-images.githubusercontent.com/5820773/84361883-a2217080-abcc-11ea-89b8-d03e989664cd.png)

The page has an UTF-8 header, so that seems all right. Is there something going wrong with the encodings along the way in the Gradle processing?

**Comment by ndw** [comment]
That seems unlikely, though it could be Windows uses some borked up code page or something. Can you send me the source and the output in a zip file?

**Comment by xatapult** [comment]
[UTF-8-source-target.zip](https://github.com/xproc/xproc.org/files/4763679/UTF-8-source-target.zip)

Here it is

**Comment by ndw** [comment]
I can't explain why or how Windows messes up the encoding :-(

**Comment by xatapult** [comment]
All right, I circumvented it already.
