### ISSUE TITLE
Specifying a page title is not possible

### ISSUE THREAD

**Issue by xatapult** [xproc/xproc.org#11]
I want to add a specific title to a page *and* use the `main.xml` header.

At the top of the Markdown page there is a piece of XML:

```
<pubmeta>
<header>main</header>
<title>XProc 3.0 - Home</title>
</pubmeta>
```

The `<title>` alters the page title but does not insert a `<h1>` with this title at the top of the page.

When I manually insert an `<h1>My title</h1>`  at the top of the page it disappears in the build process (strangely enough an `<h2>...</h2>` stays in...)

The Markdown title markers `#`, `##` etc. are not recognized by the build process.

So I'm stuck.

I would prefer that an automatic `<h1>` would be inserted at the top of the page with the contents of the `pubmeta/title` element.

**Comment by xatapult** [comment]
@ndw If you can tell me in a nutshell where the magic happens I could try to fix some of this myself?

**Comment by ndw** [comment]
It's just XProc pipelines in tools/xpl

**Comment by xatapult** [comment]
Fixed.
