### ISSUE TITLE
Responsive design is broken

### ISSUE THREAD

**Issue by ndw** [xproc/xproc.org#13]
The new design doesn't handle narrow displays correctly

**Comment by xatapult** [comment]
? What do you mean?

Only the logo disappears on narrow display. We can fix that again.

**Comment by ndw** [comment]
Indeed, it's not as bad as I first thought. The title goes away on the narrow page because you've pulled it out of the header. (In as much as I think the title should be above the menu)

**Comment by xatapult** [comment]
@ndw Based on your last remark I think we can close this one?

Or do you think we need to improve the responsiveness?
