### ISSUE TITLE
xproc.org doesn’t build automatically

### ISSUE THREAD

**Issue by gimsieke** [xproc/xproc.org#38]
Erik accepted #37 a while ago, but the site didn’t update. README.md says that the build is done by CircleCI. Maybe this mechanism needs to be updated to use a Github-native CI/CD pipeline.

**Comment by xatapult** [comment]
The build failed. I notified Norm (who created the stuff that does this)

 

From: Gerrit Imsieke ***@***.***> 
Sent: Wednesday, 15 May 2024 13:26
To: xproc/xproc.org ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xproc/xproc.org] xproc.org doesn’t build automatically (Issue #38)

 

Erik accepted #37 <https://github.com/xproc/xproc.org/pull/37>  a while ago, but the site didn’t update. README.md says that the build is done by CircleCI. Maybe this mechanism needs to be updated to use a Github-native CI/CD pipeline.

**Comment by ndw** [comment]
Sorry, the access token expired. I've refreshed it and re-run the build.
