### ISSUE TITLE
3.0 additional spec links wrong (?)

### ISSUE THREAD

**Issue by xatapult** [xproc/xproc.org#45]
I think some links on the XProc specification page https://xproc.org/specifications.html are mistaken. If you click on one of the links of the additional specifications listed under 3.0 (bottom of the page), you land on a 3.1 specification… For instance, https://spec.xproc.org/master/head/run/

Even if there’s no difference, shouldn’t there be separate, frozen, 3.0 specs? Are these available?

I don't mind repairing this, but can anybody point me to whether these 3.0 docs for the additional specs exist and what their links are?

**Comment by ndw** [comment]
There were never any final 3.0 versions of the additional specifications, so the only thing that page has ever pointed to are the editorial drafts. I've rolled all the editorial drafts forward to 3.1. Having a 3.1 last call branch that was different from the current editorial drafts seemed like a recipe for divergence that we'd regret later.

I can go back and make a 3.0-editorial-drafts-branch if you think it's necessary.

**Comment by gimsieke** [comment]
I don’t think it’s necessary. If people stumble across this and are confused, they can ask and we can explain.

**Comment by xatapult** [comment]
> Having a 3.1 last call branch that was different from the current editorial drafts seemed like a recipe for divergence that we'd regret later.

I agree. 

It just seems odd to me that we have a frozen 3.0 core spec and standard steps spec and no frozen 3.0 additional step specs. But maybe we never froze these additional specs?

**Comment by ndw** [comment]
Nope. And going through the motions to make them more than editorial drafts for 3.0 just before we publish 3.1 didn't seem worth the effort.

**Comment by xatapult** [comment]
All right. Agreed.
