### ISSUE TITLE
Remove 3.0 reference in page titles?

### ISSUE THREAD

**Issue by xatapult** [xproc/xproc.org#46]
Maybe we should remove the explicit **3.0** in the titles of the pages? Somewhere soon we're on 3.1 and who knows what happens next. 

So let this site be the *general* XProc site...

**Comment by ndw** [comment]
I'm okay with that. It would probably be good to leave some indication that the focus is on 3.0+ and not 1.0.

**Comment by xatapult** [comment]
We can do that by adding some text here and there. If nobody objects I'll give it a try next week.

**Comment by ndw** [comment]
👍
