### ISSUE TITLE
Add learning materials page

### ISSUE THREAD

**Issue by xatapult** [xproc/xproc.org#6]
I would like to add a page with “learning materials” (or whatever title) for XProc 3.0 to the main site https://xproc.org/ that lists all available help, like the xml.com articles, the webinar videos from Markup Uk, our XML Prague appearances, etc. It would lower the barrier for using it.

Of course I would like to have the book advertised as well, but maybe we only want *free* materials listed?

IMHO, this home page needs an update anyway.

**Comment by xml-project** [comment]
I already added a link to your book a while ago, so I would not restrict the "materials" to gratis material.
In general: 👍

**Comment by ndw** [comment]
Yes, by all means.
